### PR TITLE
AutoCommand and AutoScoreboard

### PR DESCRIPTION
**Pull request by aaaasdfghjkllll**
Very useful for griefing

original code btw

### CODE REVIEW

**Comment by etianl** [comment]
testing this now, wat is even macro mode in autocommand? How does it work?

**Comment by aaaasdfghjkllll** [comment]
In AutoCommand, macro mode runs a macro when permissions are detected, so if people have macros to run commands they can utilize AutoCommand to run it for them

**Comment by aaaasdfghjkllll** [comment]
also your "smol autoscoreboard bugfix" commit is not necessary, the module gets toggled at the end

**Comment by etianl** [comment]
If "finished" is true and disable-on-finish is also true the module would not turn itself off, it just feels better this way so the button always turns itself off when the disable-on-finish is enabled

**Comment by aaaasdfghjkllll** [comment]
Wouldn't it still get to the `if(disableOnFinish.get()) toggle();` part at the end tho?

**Comment by etianl** [comment]
no it did not. Also I hit enter before finishing the last commit description lol I meant to mention that I initialized "finished" as false to prevent another smol bug that arose from that if statement I stuck in there

**Comment by etianl** [comment]
I made the auto command have a full auto option to repeat commands on a tick delay if one chooses. Are we ready to merge it now or do you want to change anything?

**Comment by aaaasdfghjkllll** [comment]
yeah we can merge now, if I have anything else I'll make another pull request

**Pull request merged**
