### PR TITLE
Add .crash command, "Crash Other Players" option to OPServerKillModule and optimize AutoScoreboard

### PR DESCRIPTION
**Pull request by aaaasdfghjkllll**

### CODE REVIEW

**Comment by etianl** [comment]
you killed my if statements in OPServerKillModule which handeled which options were enabled. Also the tick delay in op server kill module is required so you can put a greater delay between commands to prevent getting kicked for spamming on some servers. The other changes look okay tho

**Comment by etianl** [comment]
Oh and the max randomTickSpeed value is "999999999" anything higher the game won't accept as a gamerule

**Comment by aaaasdfghjkllll** [comment]
The max randomTickSpeed limit is 2147483647, and the if statements are still there, and I also don't think tick delay is needed, I run a lot of commands on a lot of servers at the same time and I have never been kicked for it

**Comment by etianl** [comment]
image

**Comment by etianl** [comment]
tick delay might be needed on some server, I'm gonna stick it back in  there with your one added option if you aren't lol

**Comment by etianl** [comment]
oops wrong button

**Pull request merged**
